### PR TITLE
FEATURE: Add mechanism to automatically reload the page tree

### PR DESCRIPTION
**Pull request by grebaldi**

### CODE REVIEW

**Comment by mficzel** [comment]
Great feature but i dislike two points:

- If i get this right this will reload the pageTree always if a page is loaded in the backend.
- The JS is always included. That should be limited to the backend.

**Comment by mficzel** [comment]
Great feature but i dislike two points:

- If i get this right this will reload the pageTree always if a page is loaded in the backend.
- The JS is always included. That should be limited to the backend.

**Comment by mficzel** [comment]
Great feature but i dislike two points:
- If i get this right this will reload the pageTree always if a page is loaded in the backend.
- The JS is always included. That should be limited to the backend.

**Comment by grebaldi** [comment]
Update: The pagetree now only gets reloaded, when the document has a Critical Mass configuration and has recently been modified. Besides that, the repsective JavaScript only gets loaded in backend.

**Pull request merged**
